# Use the official Node.js image as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY BiteSpeed/package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the app's source code
COPY BiteSpeed/src/../

# Expose the port that the Express app will listen on
EXPOSE 3000

# Start the Express app
CMD ["node", "server.js"]
