version: '3'
services:
  # Service for the Node.js app
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # Add any environment variables needed for the app, e.g., database connection settings
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: Bitespeed_Contacts
    networks:
      - app_network

  # Service for the MySQL database
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: Bitespeed_Contacts
    networks:
      - app_network

networks:
  app_network:
